"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Steve Mosley"
email = "steve@starter4ten.com"

[ui]
default-command = "log"

[merge-tools.bc] 
program = "bcomp" # On MacOS, this should be "bcomp".
edit-args = ["$left", "$right", "-ro1", "-expandall"]
merge-args = ["$left", "$right", "$base", "$output", "-automerge", "-reviewconflicts"]

[git]
private-commits = "description(glob:'WIP:*')"

[template]
push-bookmark-prefix = "steve/push-"

[aliases]
f = ["git", "fetch"]
pu = ["git", "push"]
la = ["log", "-r all"]

[remotes.origin]
auto-track-bookmarks = "glob:*"

[revsets]
bookmark-advance-to = '@-'
log = "trunk()..@ | trunk()"

[revset-aliases]
all = "present(@) | ancestors(immutable_heads().., 2) | present(trunk())"
