#!/bin/sh
# Link all dotfiles into the home dir

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

ln -fs $DOTFILESDIR/ssh ~/.ssh
ln -fs $DOTFILESDIR/Brewfile ~/.Brewfile
ln -fs $DOTFILESDIR/tmux.conf ~/.tmux.conf
ln -fs $DOTFILESDIR/zshrc ~/.zshrc
ln -fs $DOTFILESDIR/vimrc ~/.vimrc
ln -fs $DOTFILESDIR/hyper.js ~/.hyper.js
ln -fs $DOTFILESDIR/tool-versions ~/.tool-versions
ln -fs $DOTFILESDIR/nvim ~/.config/nvim

ln -fs $DOTFILESDIR/git/gitignore_global ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global
