#!/bin/sh
# Link all dotfiles into the home dir

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

ln -fs $DOTFILESDIR/Brewfile ~/.Brewfile
ln -fs $DOTFILESDIR/tmux.conf ~/.tmux.conf
ln -fs $DOTFILESDIR/zshrc ~/.zshrc
ln -fs $DOTFILESDIR/vimrc ~/.vimrc
