#!/bin/sh
# Link all dotfiles into the home dir

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

ln -fs $DOTFILESDIR/ssh ~/.ssh
ln -fs $DOTFILESDIR/Brewfile ~/.Brewfile
ln -fs $DOTFILESDIR/tmux.conf ~/.tmux.conf
ln -fs $DOTFILESDIR/zshrc ~/.zshrc

mkdir -p ~/.config/mise
ln -fs $DOTFILESDIR/mise.toml ~/.config/mise/config.toml

ln -fs $DOTFILESDIR/git/gitignore_global ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global
