#!/bin/sh
# Keep shit up to date

# First Update what we already have
brew bundle install
brew update
brew upgrade

# First make sure brew file is update
brew bundle check --global || brew bundle --global

