#!/bin/sh
# Keep shit up to date

# First Update what we already have
brew update
brew upgrade

# Install latest from Brewfile and remove anything not in Brewfile
brew bundle install
brew bundle --force cleanup

