#!/bin/sh
# Application setup after everything has been installed

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

# Setup oh my zsh
if [ ! -d "$HOME/.oh-my-zsh/" ]; then
  echo "Installing Oh My ZSH"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  ln -fs $DOTFILESDIR/zshrc ~/.zshrc
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
    git clone git://github.com/zsh-users/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/themes/spaceship-prompt" ]; then
    git clone https://github.com/denysdovhan/spaceship-prompt.git "$HOME/.oh-my-zsh/custom/themes/spaceship-prompt"
    ln -s "$HOME/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme" "$HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
fi


# Setup Tmux
mkdir -p $HOME/.tmux/plugins
if [ ! -d  $HOME/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# Setup vim
if [ ! -d $HOME/.vim/autoload ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Setup nvm
if [ ! -d $HOME/.nvm ]; then
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
fi

# Make sure we've accepted xcode license
sudo xcodebuild -license accept

# Global things
## Dont make dsstore files
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE

## Make function keys act like normal
defaults write NSGlobalDomain com.apple.keyboard.fnState -bool TRUE;

## Expand print dialog by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool TRUE;

## Show IP address, hostname, OS version when clicking the clock in the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

## Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

## Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

## Automatically illuminate built-in MacBook keyboard in low light
defaults write com.apple.BezelServices kDim -bool true

## Turn off keyboard illumination when computer is not used for 5 minutes
defaults write com.apple.BezelServices kDimTime -int 300

## Enable full keyboard access for all controls"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Setup Dock
## Only show active apps
defaults write com.apple.dock static-only -bool TRUE;

## Indicate when apps are hidden
defaults write com.apple.dock showhidden -bool TRUE;

## Set Auto hide
defaults write com.apple.dock autohide -bool TRUE; 

## Configure the AutoHide
defaults write com.apple.dock autohide-time-modifier -float 1; 

## Dock position
defaults write com.apple.dock orientation -string right; 

## Simple UI
defaults write com.apple.dock no-glass -bool TRUE; 

killall Dock

# Setup Finder

## Disable file extension warnings.
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool FALSE; 

## Show all file name extensions
defaults write com.apple.finder AppleShowAllExtensions -bool TRUE; 

## Show Status Bar
defaults write com.apple.finder ShowStatusBar -bool true

# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

## Unhide library
chflags nohidden ${home}/Library

killall Finder

# Hot Corners
## Top Left Display Sleep
defaults write com.apple.dock wvous-tl-corner -int 10
defaults write com.apple.dock wvous-tl-modifier -int 0

# SSH
sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
